name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install project
        run: poetry install --no-interaction --extras "plot docs"

      - name: Run Ruff (Linting)
        run: poetry run ruff check .

      - name: Run Tests (Pytest)
        run: poetry run pytest

      - name: Build docs
        run: poetry run sphinx-build -b html docs docs/_build/html
